//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarZon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelDetail
    {
        public int Id { get; set; }
        public string DocNum { get; set; }
        public string DocEntry { get; set; }
        public Nullable<decimal> MainQty { get; set; }
        public Nullable<decimal> AddonQty { get; set; }
        public Nullable<int> Fabric { get; set; }
        public string LabelNo { get; set; }
        public string MainlabelNo { get; set; }
        public string Lbno { get; set; }
        public string WebSO { get; set; }
        public string Tno { get; set; }
    }
}
