//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarZon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesurement
    {
        public int id { get; set; }
        public string MeasurmentId { get; set; }
        public string MeasurmentName { get; set; }
        public string mesurementDetails { get; set; }
        public string imagepath { get; set; }
        public string LineId { get; set; }
    }
}
