//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarZon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCLG
    {
        public int ClgCode { get; set; }
        public string CardCode { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CntctDate { get; set; }
        public Nullable<int> CntctTime { get; set; }
        public Nullable<System.DateTime> Recontact { get; set; }
        public string Closed { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string ContactPer { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public Nullable<short> CntctSbjct { get; set; }
        public string Transfered { get; set; }
        public string DocType { get; set; }
        public string DocNum { get; set; }
        public string DocEntry { get; set; }
        public string Attachment { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> AttendUser { get; set; }
        public Nullable<int> CntctCode { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public string Action { get; set; }
        public string Details { get; set; }
        public Nullable<short> CntctType { get; set; }
        public Nullable<short> Location { get; set; }
        public Nullable<int> BeginTime { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public string DurType { get; set; }
        public Nullable<int> ENDTime { get; set; }
        public string Priority { get; set; }
        public string Reminder { get; set; }
        public Nullable<decimal> RemQty { get; set; }
        public string RemType { get; set; }
        public Nullable<int> OprId { get; set; }
        public Nullable<short> OprLine { get; set; }
        public Nullable<System.DateTime> RemDate { get; set; }
        public Nullable<short> RemTime { get; set; }
        public string RemSented { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> status { get; set; }
        public string personal { get; set; }
        public string inactive { get; set; }
        public string tentative { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string room { get; set; }
        public string parentType { get; set; }
        public Nullable<int> parentId { get; set; }
        public Nullable<int> prevActvty { get; set; }
        public Nullable<int> AtcEntry { get; set; }
        public string RecurPat { get; set; }
        public string EndType { get; set; }
        public Nullable<System.DateTime> SeStartDat { get; set; }
        public Nullable<System.DateTime> SeEndDat { get; set; }
        public Nullable<int> MaxOccur { get; set; }
        public Nullable<int> Interval { get; set; }
        public string Sunday { get; set; }
        public string Monday { get; set; }
        public string Tuesday { get; set; }
        public string Wednesday { get; set; }
        public string Thursday { get; set; }
        public string Friday { get; set; }
        public string Saturday { get; set; }
        public string SubOption { get; set; }
        public Nullable<int> DayInMonth { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> SeriesNum { get; set; }
        public Nullable<System.DateTime> OrigDate { get; set; }
        public string IsRemoved { get; set; }
        public Nullable<System.DateTime> LastRemind { get; set; }
        public Nullable<short> AssignedBy { get; set; }
        public string AddrName { get; set; }
        public string AddrType { get; set; }
        public Nullable<int> AttendEmpl { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public Nullable<short> NextTime { get; set; }
        public Nullable<int> OwnerCode { get; set; }
        public Nullable<int> AttendReci { get; set; }
        public Nullable<int> ActType { get; set; }
        public string LaborItem { get; set; }
        public string ResCode { get; set; }
        public string FIPROJECT { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public string DPPStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string EncryptIV { get; set; }
        public string U_User { get; set; }
        public string U_AssignBy { get; set; }
    }
}
