//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarZon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCST
    {
        public string Code { get; set; }
        public string Country { get; set; }
        public string Name { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> eCode { get; set; }
        public string GNRECode { get; set; }
        public string GSTCode { get; set; }
        public string GSTIsUT { get; set; }
        public Nullable<short> GroupCode { get; set; }
    }
}
