//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarZon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OITB
    {
        public short ItmsGrpCod { get; set; }
        public string ItmsGrpNam { get; set; }
        public string Locked { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string BalInvntAc { get; set; }
        public string SaleCostAc { get; set; }
        public string TransferAc { get; set; }
        public string RevenuesAc { get; set; }
        public string VarianceAc { get; set; }
        public string DecreasAc { get; set; }
        public string IncreasAc { get; set; }
        public string ReturnAc { get; set; }
        public string ExpensesAc { get; set; }
        public string EURevenuAc { get; set; }
        public string EUExpensAc { get; set; }
        public string FrRevenuAc { get; set; }
        public string FrExpensAc { get; set; }
        public string ExmptIncom { get; set; }
        public Nullable<short> CycleCode { get; set; }
        public string Alert { get; set; }
        public string PriceDifAc { get; set; }
        public string ExchangeAc { get; set; }
        public string BalanceAcc { get; set; }
        public string PurchaseAc { get; set; }
        public string PAReturnAc { get; set; }
        public string PurchOfsAc { get; set; }
        public string ShpdGdsAct { get; set; }
        public string VatRevAct { get; set; }
        public string DecresGlAc { get; set; }
        public string IncresGlAc { get; set; }
        public string InvntSys { get; set; }
        public string PlaningSys { get; set; }
        public string PrcrmntMtd { get; set; }
        public Nullable<short> OrdrIntrvl { get; set; }
        public Nullable<decimal> OrdrMulti { get; set; }
        public Nullable<decimal> MinOrdrQty { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public string StokRvlAct { get; set; }
        public string StkOffsAct { get; set; }
        public string WipAcct { get; set; }
        public string WipVarAcct { get; set; }
        public string CostRvlAct { get; set; }
        public string CstOffsAct { get; set; }
        public string ExpClrAct { get; set; }
        public string ExpOfstAct { get; set; }
        public string Object { get; set; }
        public Nullable<int> logInstanc { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<short> userSign2 { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string ARCMAct { get; set; }
        public string ARCMFrnAct { get; set; }
        public string ARCMEUAct { get; set; }
        public string ARCMExpAct { get; set; }
        public string APCMAct { get; set; }
        public string APCMFrnAct { get; set; }
        public string APCMEUAct { get; set; }
        public string RevRetAct { get; set; }
        public string ItemClass { get; set; }
        public Nullable<int> OSvcCode { get; set; }
        public Nullable<int> ISvcCode { get; set; }
        public Nullable<int> ServiceGrp { get; set; }
        public Nullable<int> NCMCode { get; set; }
        public string MatType { get; set; }
        public Nullable<int> MatGrp { get; set; }
        public string ProductSrc { get; set; }
        public string NegStckAct { get; set; }
        public string StkInTnAct { get; set; }
        public string PurBalAct { get; set; }
        public string WhICenAct { get; set; }
        public string WhOCenAct { get; set; }
        public string WipOffset { get; set; }
        public string StockOffst { get; set; }
        public Nullable<int> UgpEntry { get; set; }
        public Nullable<int> IUoMEntry { get; set; }
        public Nullable<int> ToleranDay { get; set; }
        public string RuleCode { get; set; }
        public string CompoWH { get; set; }
        public string FreeChrgSA { get; set; }
        public string FreeChrgPU { get; set; }
        public string RawMtrl { get; set; }
        public string U_Alteration { get; set; }
    }
}
