//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarZon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSTC
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Freight { get; set; }
        public Nullable<short> UserSign { get; set; }
        public string ValidForAR { get; set; }
        public string ValidForAP { get; set; }
        public Nullable<int> TfcId { get; set; }
        public string Lock { get; set; }
        public string TaxIcms { get; set; }
        public string IsItmLevel { get; set; }
        public string CfopIn { get; set; }
        public string CfopOut { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string FADebit { get; set; }
        public string IsSystem { get; set; }
    }
}
