//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarZon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportaionhead
    {
        public int Tno { get; set; }
        public Nullable<System.DateTime> Tdate { get; set; }
        public string outletfrom { get; set; }
        public string outletto { get; set; }
        public string MeasurmentsDetails { get; set; }
        public string Tstatus { get; set; }
        public string Pickupuser { get; set; }
        public string orderno { get; set; }
        public string Username { get; set; }
        public string userid { get; set; }
    }
}
